(defun function-arity (fn)
  "获取函数`fn'所允许的最小和最大参数个数,参见`subr-arity'但fn可以是任意函数"
  (setq fn (indirect-function fn))
  (if (subrp fn)
	  (subr-arity fn)
	(require 'help)
	(require 'cl)
	(let* ((fn-arglist (help-function-arglist fn))
		   (min-arg (or (cl-position-if (lambda (x)
										  (member x '(&optional &rest))) fn-arglist)
						(length fn-arglist)))
		   (max-arg (cond ((member '&rest fn-arglist)
						   'many)
						  ((member '&optional fn-arglist)
						   (1- (length fn-arglist)))
						  (t min-arg))))
	  (cons min-arg max-arg))))

(provide 'elisp-helper)
